@startuml

folder "Ovis" as ovis {
    [description]
    [bringup]
}

package "Ovis description" as description {
    [launch.py]
}

package "Ovis Bringup" as bringup {
    [sim.launch.py]
}

package "Ovis Manipulation" as manipulation {
    [moveit.launch.py]
}

@enduml
